## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
codecov: true
os:
  - linux
#  - osx
julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
notifications:
  email: false
git:
  depth: 99999999

# Integration with JuMP-dev gitter channel
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/cb052648b833828852b4
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --project=docs/ -e 'import Pkg; Pkg.instantiate(); Pkg.develop(Pkg.PackageSpec(path=pwd()))'
        - julia --project=docs/ docs/make.jl
      after_success: skip
